name: PR_unit_tests

on:
  pull_request:
    branches:
      - 'master'

env:
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASS: ${{ secrets.KEY_PASS }}

jobs:
  Unit-test:
    name: Run unit tests on PR in main
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test