name: Test and Build Artifacts on Release

on:
  push:
    branches:
      - master

env:
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
  KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
  KEY_PASS: ${{ secrets.KEY_PASS }}

jobs:
  Build_apk_aab:
    if: startsWith(github.event.head_commit.message, 'Release')
    name: Build apk and aab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: checkout keystore repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.KEYSTORE_REPO }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: app/keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build release APK and AAB after testing
        run: |
          ./gradlew test
          ./gradlew assembleRelease
          ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload AAB
        uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Deploy on my server by SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: app/build/outputs/apk/release/app-release.apk
          remote-dir: ${{ secrets.SFTP_DIR }}